escamboapp/config/routes.rb
Rails.application.routes.draw do
#reduzi ainda mais o link no navegador
  get 'backoffice', to: 'backoffice/dashboard#index'

  namespace :backoffice do
    # resources e o nome cria todas as rotas para categories, mas nesse caso, informo que não quero o show e nem destroy
    resources :categories, except: [:show, :destroy]
    resources :admins, except: [:show]
    get 'dashboard', to: 'dashboard#index'
  end
  namespace :site do
    get 'home', to: 'home#index'
  end


  devise_for :admins, :skip => [:registrations]
  devise_for :members

  root 'site/home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

escamboapp/app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :category
  belongs_to :member
end

escamboapp/app/models/admin.rb
class Admin < ApplicationRecord
  enum role: [:full_access, :restricted_access]

  validates :password, confirmation: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def role_br
	   if self.role == 'full_access'
	   	 'Acesso Completo'
	   else
	   	 'Acesso Restrito'
	   end       	
  end       
end

escamboapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

escamboapp/app/models/category.rb
class Category < ApplicationRecord
	validates_presence_of :description
end

escamboapp/app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

escamboapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout_by_resource

  protected

  def layout_by_resource
  	if devise_controller? && resource_name == :admin
  		"backoffice_devise"
  	else 
  		"application"
  	end
  end	
end

escamboapp/app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController
before_action :set_admin, only: [:edit, :update, :destroy] 

  def index
  	@admins = Admin.order :id
  end

  def new
  	@admin = Admin.new
  end

  def create
  	@admin = Admin.new(params_admin)  	
  	#se salvar, redireciona para a rota abaixo com a mensagem
  	if @admin.save 
  		redirect_to backoffice_admins_path, notice: "O administrador (#{@admin.email}) foi cadastrada com sucesso!"
  	else
  	    render new
    end
  end
   
  def edit
  end

  def destroy
  	admin_email = @admin.email
  	if @admin.destroy 
  		redirect_to backoffice_admins_path, notice: "O administrador (#{admin_email}) foi excluído com sucesso!"
  	else
  	    render new
    end
  end

  def update
  	passwd = params[:admin][:password]
  	passwd_confirmation = params[:admin][:password_confirmation]

  	if (passwd.blank? && passwd_confirmation.blank?)
  		params[:admin].delete(:password)
  		params[:admin].delete(:password_confirmation)
  	end

 	if @admin.update(params_admin)
       redirect_to backoffice_admins_path, notice: "A categoria (#{@admin.email}) foi atualizada com sucesso!"
  	else
      render :edit
  	end	

  end


  private

  def params_admin
  	params.require(:admin).permit(:name, :email, :password, :password_confirmation, :role)
  end

  def set_admin
  	@admin = Admin.find(params[:id])
  end
end

escamboapp/app/controllers/backoffice/categories_controller.rb
class Backoffice::CategoriesController < BackofficeController
  before_action :set_category, only: [:edit, :update] 

  def index
  	@categories = Category.order :id
  end

  def new
  	@category = Category.new
  end

  def create
  	@category = Category.new(params_category)  	
  	#se salvar, redireciona para a rota abaixo com a mensagem
  	if @category.save 
  		redirect_to backoffice_categories_path, notice: "A categoria (#{@category.description}) foi cadastrada com sucesso!"
  	else
  	    render new
    end
  end
   
  def edit
  end

  def update
  	if @category.update(params_category)
       redirect_to backoffice_categories_path, notice: "A categoria (#{@category.description}) foi atualizada com sucesso!"
  	else
      render :edit
  	end	

  end


  private

  def params_category
  	params.require(:category).permit(:description)
  end

  def set_category
  	@category = Category.find(params[:id])
  end
end

escamboapp/app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < BackofficeController
 def index
  	@categories = Category.all
  end
end

escamboapp/app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout "backoffice"

end

escamboapp/app/controllers/site/home_controller.rb
class Site::HomeController < ApplicationController
layout "site"
  def index
  	@categories = Category.all
  end
end

escamboapp/app/helpers/application_helper.rb
module ApplicationHelper
end

escamboapp/app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
end

escamboapp/app/helpers/backoffice/categories_helper.rb
module Backoffice::CategoriesHelper
end

escamboapp/app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

escamboapp/app/helpers/site/home_helper.rb
module Site::HomeHelper
end

escamboapp/app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

escamboapp/app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

escamboapp/app/views/backoffice/admins/edit.html.erb
<h1> Edição de Administrador </h1>
<%= render partial: "backoffice/admins/shared/form", locals: {action: "editar"} %>

escamboapp/app/views/backoffice/admins/index.html.erb
<h1>Backoffice::Dashboard#index</h1>
<p>Find me in app/views/backoffice/dashboard/index.html.erb</p>

<%=current_admin.email %>
Categorias
<div class="panel panel-default">
	<div class="panel-heading">
		<h1>Administradores</h1>
        <%= link_to new_backoffice_admin_path, class:"btn btn-success btn-circle" do %>
            <i class="fas fa-plus"></i>
        <% end %>   
	</div><br/>
	<div style=".border-left-primary">ffre</div>
	<div class="panel-body">
		<div class="table-responsive">
			<table class= "table-striped table-bordered table-hover" width="100%">
			<thead>
				<tr>
				<th>#</th>
				<th>Nome</th>
				<th>E-mail</th>
				<th>Tipo de Acesso</th>
				<th>Editar</th>
				<th>Excluir</th>
				</tr>
			</thead>
			<tbody>
				<% @admins.each do |admin| %>
				<tr>
					<td><%= admin.id %></td>
					<td><%= admin.name %></td>
					<td><%= admin.email %></td>
					<td><%= admin.role_br %></td>
					<td>
						<!--<a href="#" class="btn btn-info btn-circle"><i class="fas fa-info-circle"></i></a>-->
						<%= link_to edit_backoffice_admin_path(admin), class:"btn btn-primary btn-circle" do %>
                            <i class="far fa-edit"></i>
                        <% end %>
					</td>
					<td> 
					<% if current_admin.id != admin.id %>	
						<%= link_to backoffice_admin_path(admin), method: :delete, class:"btn btn-danger btn-circle", data: {confirm: "Você deseja realmente excluir #{admin.email}?"} do %>
                           <i class="far fa-trash-alt"></i>
                        <% end %>
                     <% else %>
                        <%= link_to '#', disabled: "disabled", title: "Logado", class:"btn btn-danger btn-circle" do %>
                           <i class="far fa-trash-alt"></i>
                        <% end %>
                     <% end %>   
                    </td>
				</tr>
				<% end %>
			</tbody>
			</table>
		</div>
	</div>
</div>	

escamboapp/app/views/backoffice/admins/new.html.erb
<h1> Novo administrador </h1>
<%= render partial: "backoffice/admins/shared/form", locals: {action: "novo"} %>

escamboapp/app/views/backoffice/admins/shared/_form.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
	<% if @admin.errors.any? %>
        <div class="alert alert-danger" role="alert">
        <ul>	
	  		<% @admin.errors.full_messages.each do |message| %>
				<li><%= message %></li>
	  		<% end %>
  	    </ul>
		</div>
    <% end %>
	</div>
	<div class="panel-body">
	  <div class="form-group">
	    <%= form_for([:backoffice, @admin]) do  |f|%>
	    <label for="formGroupExampleInput"><b>Nome</b></label>
	     <%= f.text_field :name, class:"form-control", id:"formGroupExampleInput", placeholder:"Exemplo João Pedro" %>
	    <label for="formGroupExampleInput"><b>Email</b></label>
	     <%= f.text_field :email, class:"form-control", id:"formGroupExampleInput", placeholder:"Exemplo joao@gmail.com" %>
	     <label for="formGroupExampleInput"><b>Senha</b></label>
	     <%= f.password_field :password, class:"form-control", id:"formGroupExampleInputPass" %>
	     <label for="formGroupExampleInput"><b>Confirmação de Senha</b></label>
	     <%= f.password_field :password_confirmation, class:"form-control", id:"formGroupExampleInputPassConf" %>
	     	<% if (action == "novo") %>
			<%= f.submit "Salvar Administrador" %>
			<% else %>
			<%= f.submit "Editar Administrador" %>
			<% end %>
	    <% end %>
	  </div>
	</div>
</div>	

escamboapp/app/views/backoffice/categories/edit.html.erb
<h1> Edição de Categoria </h1>
<%= render partial: "backoffice/categories/shared/form", locals: {action: "editar"} %>

escamboapp/app/views/backoffice/categories/index.html.erb
<h1>Backoffice::Dashboard#index</h1>
<p>Find me in app/views/backoffice/dashboard/index.html.erb</p>

<%=current_admin.email %>
Categorias
<div class="panel panel-default">
	<div class="panel-heading">
		<h1>Categorias</h1>
        <%= link_to new_backoffice_category_path, class:"btn btn-success btn-circle" do %>
            <i class="fas fa-plus"></i>
        <% end %>   
	</div><br/>
	<div style=".border-left-primary">ffre</div>
	<div class="panel-body">
		<div class="table-responsive">
			<table class= "table-striped table-bordered table-hover" width="100%">
			<thead>
				<tr>
				<th>#</th>
				<th>Descrição</th>
				<th>Editar</th>
				<th>Excluir</th>
				</tr>
			</thead>
			<tbody>
				<% @categories.each do |category| %>
				<tr>
					<td><%= category.id %></td>
					<td><%= category.description %></td>
					<td>
						<!--<a href="#" class="btn btn-info btn-circle"><i class="fas fa-info-circle"></i></a>-->
						<%= link_to edit_backoffice_category_path(category), class:"btn btn-primary btn-circle" do %>
                            <i class="far fa-edit"></i>
                        <% end %>
					</td>
					<td> 
					         <button type="button" disabled="disabled" class="btn btn-danger btn-circle"><i class="far fa-trash-alt"></i>
                            </button>
                    </td>
				</tr>
				<% end %>
			</tbody>
			</table>
		</div>
	</div>
</div>	

escamboapp/app/views/backoffice/dashboard/index.html.erb
<h1>Backoffice::Dashboard#index</h1>
<p>Find me in app/views/backoffice/dashboard/index.html.erb</p>

<%=current_admin.email %>

escamboapp/app/views/layouts/backoffice_shared/_exit_confirmation.html.erb
  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Deseja realmente sair?</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <%= link_to destroy_admin_session_path, method: :delete do %>
          <div class="btn btn-primary" >Sair</div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <a class="btn btn-primary" href="login.html">Logout</a>

escamboapp/app/views/layouts/backoffice_shared/_sidebar.html.erb
<!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item">
        <%= link_to backoffice_path do%>
          <div class="nav-link">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span>
          </div>
          <%end%>
      </li>

      <li class="nav-item">
        <%= link_to backoffice_categories_path do%>
          <div class="nav-link">
            <i class="fas fa-th-list"></i>
            <span>Categorias</span> 
          </div>
        <% end %>
      </li>      

      <li class="nav-item">
        <%= link_to backoffice_admins_path do%>
          <div class="nav-link">
            <i class="fas fa-users"></i>
            <span>Administradores</span> 
          </div>
        <% end %>
      </li>   
      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Interface
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-fw fa-cog"></i>
          <span>Components</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Custom Components:</h6>
            <a class="collapse-item" href="buttons.html">Buttons</a>
            <a class="collapse-item" href="cards.html">Cards</a>
          </div>
        </div>
      </li>

      <!-- Nav Item - Utilities Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
          <i class="fas fa-fw fa-wrench"></i>
          <span>Utilities</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Custom Utilities:</h6>
            <a class="collapse-item" href="utilities-color.html">Colors</a>
            <a class="collapse-item" href="utilities-border.html">Borders</a>
            <a class="collapse-item" href="utilities-animation.html">Animations</a>
            <a class="collapse-item" href="utilities-other.html">Other</a>
          </div>
        </div>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Addons
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item active">
        <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
          <i class="fas fa-fw fa-folder"></i>
          <span>Pages</span>
        </a>
        <div id="collapsePages" class="collapse show" aria-labelledby="headingPages" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Login Screens:</h6>
            <a class="collapse-item" href="login.html">Login</a>
            <a class="collapse-item" href="register.html">Register</a>
            <a class="collapse-item" href="forgot-password.html">Forgot Password</a>
            <div class="collapse-divider"></div>
            <h6 class="collapse-header">Other Pages:</h6>
            <a class="collapse-item" href="404.html">404 Page</a>
            <a class="collapse-item active" href="blank.html">Blank Page</a>
          </div>
        </div>
      </li>

      <!-- Nav Item - Charts -->
      <li class="nav-item">
        <a class="nav-link" href="charts.html">
          <i class="fas fa-fw fa-chart-area"></i>
          <span>Charts</span></a>
      </li>

      <!-- Nav Item - Tables -->
      <li class="nav-item">
        <a class="nav-link" href="tables.html">
          <i class="fas fa-fw fa-table"></i>
          <span>Tables</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->

escamboapp/app/views/layouts/backoffice_shared/_topbar.html.erb
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Topbar Search -->
          <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
            <div class="input-group">
              <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                  <i class="fas fa-search fa-sm"></i>
                </button>
              </div>
            </div>
          </form>
          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <li class="nav-item dropdown no-arrow d-sm-none">
              <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                  <div class="input-group">
                    <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                      <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                      </button>
                    </div>
                  </div>
                </form>
              </div>
            </li>

            <!-- Nav Item - Alerts -->
            <li class="nav-item dropdown no-arrow mx-1">
              <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bell fa-fw"></i>
                <!-- Counter - Alerts -->
                <span class="badge badge-danger badge-counter">3+</span>
              </a>
              <!-- Dropdown - Alerts -->
              <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
                <h6 class="dropdown-header">
                  Alerts Center
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="mr-3">
                    <div class="icon-circle bg-primary">
                      <i class="fas fa-file-alt text-white"></i>
                    </div>
                  </div>
                  <div>
                    <div class="small text-gray-500">December 12, 2019</div>
                    <span class="font-weight-bold">A new monthly report is ready to download!</span>
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="mr-3">
                    <div class="icon-circle bg-success">
                      <i class="fas fa-donate text-white"></i>
                    </div>
                  </div>
                  <div>
                    <div class="small text-gray-500">December 7, 2019</div>
                    $290.29 has been deposited into your account!
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="mr-3">
                    <div class="icon-circle bg-warning">
                      <i class="fas fa-exclamation-triangle text-white"></i>
                    </div>
                  </div>
                  <div>
                    <div class="small text-gray-500">December 2, 2019</div>
                    Spending Alert: We've noticed unusually high spending for your account.
                  </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
              </div>
            </li>

            <!-- Nav Item - Messages -->
            <li class="nav-item dropdown no-arrow mx-1">
              <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-envelope fa-fw"></i>
                <!-- Counter - Messages -->
                <span class="badge badge-danger badge-counter">7</span>
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="messagesDropdown">
                <h6 class="dropdown-header">
                  Message Center
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src="https://source.unsplash.com/fn_BT9fwg_E/60x60" alt="">
                    <div class="status-indicator bg-success"></div>
                  </div>
                  <div class="font-weight-bold">
                    <div class="text-truncate">Hi there! I am wondering if you can help me with a problem I've been having.</div>
                    <div class="small text-gray-500">Emily Fowler · 58m</div>
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src="https://source.unsplash.com/AU4VPcFN4LE/60x60" alt="">
                    <div class="status-indicator"></div>
                  </div>
                  <div>
                    <div class="text-truncate">I have the photos that you ordered last month, how would you like them sent to you?</div>
                    <div class="small text-gray-500">Jae Chun · 1d</div>
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src="https://source.unsplash.com/CS2uCrpNzJY/60x60" alt="">
                    <div class="status-indicator bg-warning"></div>
                  </div>
                  <div>
                    <div class="text-truncate">Last month's report looks great, I am very happy with the progress so far, keep up the good work!</div>
                    <div class="small text-gray-500">Morgan Alvarez · 2d</div>
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60" alt="">
                    <div class="status-indicator bg-success"></div>
                  </div>
                  <div>
                    <div class="text-truncate">Am I a good boy? The reason I ask is because someone told me that people say this to all dogs, even if they aren't good...</div>
                    <div class="small text-gray-500">Chicken the Dog · 2w</div>
                  </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
              </div>
            </li>

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->

            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small"><%=current_admin.email %></span>
                <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Profile
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                  Settings
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                  Activity Log
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>

          </ul>

        </nav>
        <!-- End of Topbar -->